# Generated by Django 2.2 on 2019-08-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_codee', to='App.CourseManagement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_sessionn', to='App.StudentManagement')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuss', to='App.GradeManagement')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_idd', to='App.StudentManagement')),
            ],
        ),
    ]
