# Generated by Django 2.2 on 2019-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_statustable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustable',
            name='session',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='statustable',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
