# Generated by Django 2.2 on 2019-08-09 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190807_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterUniqueTogether(
            name='coursemanagement',
            unique_together={('course_code', 'prerequisite')},
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursecodes', to='App.CourseManagement')),
                ('grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradegrades', to='App.GradeManagement')),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grademarks', to='App.GradeManagement')),
            ],
        ),
    ]
