# Generated by Django 2.2 on 2019-08-18 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20190814_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionmanagement',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterField(
            model_name='deadline',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 8, 18)),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 8, 18)),
        ),
        migrations.AlterField(
            model_name='sessionmanagement',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 8, 18)),
        ),
        migrations.AlterField(
            model_name='sessionmanagement',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 8, 18)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 18)),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='enrolled_year',
            field=models.DateField(default=datetime.date(2019, 8, 18)),
        ),
    ]
